### ISSUE TITLE
appropriately handle unicode filenames in site deploys

### ISSUE THREAD

**Issue by fool** [netlify/open-api#113]
Situation: Enterprise customer Global Citizen Year ($12k contract -  https://www.dropbox.com/s/sa2xz75t4k1d8c0/-Signed%20Global%20Citizen%20Year.pdf?dl=0) is unable to successfully deploy their site from git.  While there is another problem also blocking, this one is 1/2 of the problem.  They have unicode filenames and their deploys error like this:

`failed during stage 'deploying site': Failed to execute deploy: Upload cancelled: updates/on-walking-sharing-space-and-our-mother%c2%89s-garden/index.html`

(from https://app.netlify.com/sites/wizardly-wing-6da16b/deploys/5bac50cd73f2cf0ea39d04ca)

you can see the problem more clearly in humio:

`Failed to upload file updates/on-walking-sharing-space-and-our-mother%c2%89s-garden/index.html" build_id=5bac50cd73f2cf0ea39d04cb context=production deploy_id=5bac50cd73f2cf0ea39d04ca error="[PUT /deploys/{deploy_id}/files/{path}][422] uploadDeployFile default  u0026{Code:422 Message:Missing entry in deploy for /updates/on-walking-sharing-space-and-our-motheru0089s-garden/index.html}`

(from https://cloud.humio.com/netlify-production/search?widgetType=list-view&query=5bac50cd73f2cf0ea39d04ca%20on-walking-sharing-space&live=false&start=1537945200000&end=1538031600000&fullscreen=false)

@bcomnes tracked this down to this repo and behavior:

When you make the API call to create a deploy for files that contain unicode characters in filenames, filenames in the initial manifest need to be unescaped (== actual names), but when uploaded (PUT to the API) must be escaped since the filename is in a URL

**Comment by fool** [comment]
cc @phae guess we need to discuss this during our meeting - nobody seems to have the bandwidth to make the save for $12k

**Comment by futuregerald** [comment]
i'm unable to test this at the moment:

        make all
        swagger validate swagger.yml
        2018/10/11 13:35:56
        The swagger spec at "swagger.yml" is valid against swagger specification 2.0
        swagger generate client -A netlify -f swagger.yml -t go -c plumbing --with-flatten=full
        unknown flag `with-flatten'
        make: *** [generate] Error 1

spoke to Bret about it and he suggested I talk to Keiko. I've already re-installed my go-swagger. so no quick fix on this but if I can get this resolved I'll be able to test the PR and see if it solves the issue, or if more needs to be done.

**Comment by futuregerald** [comment]
After doing additional tests, we are unable to replicate this issue, so we're closing it. Feel free to re-open it.

**Comment by bcomnes** [comment]
Updating the build to 0.4.2 seemed to fix this bug.  Perhaps it was an internal fix on open-api.  Re-open if we run into similar symptoms.
