### ISSUE TITLE
Handle 408 timeouts better in go client / text error decoder

### ISSUE THREAD

**Issue by bcomnes** [netlify/open-api#122]
```
res, err := b.apiClient.DeployFiles(absFilePath, absFuncPath, b.Branch, b.GitRef(), b.SysLog)
```

When the retry uploads fail with a 408 you end up with an error like:

```
deploying site': Failed to execute deploy: no consumer: "text/html; charset=UTF-8"
```

Not very friendly.  We probably need to special case handle 408s since its not returning JSON messaging.

**Comment by rybit** [comment]
(1) get api to fix it :) 
(2) we should put a consumer in to print these out better. Maybe not assuming JSON?

**Comment by bcomnes** [comment]
The problem is that the API isn't generating the error, its a layer in front of the API that kills any requests over 30s if my understanding is correct.

**Comment by bcomnes** [comment]
>  we should put a consumer in to print these out better. Maybe not assuming JSON?

Not familiar with consumers yet.  Maybe we can chat about it in slack soon.

**Comment by rybit** [comment]
related to #128
