### ISSUE TITLE
Missing /oauth/token endpoint

### ISSUE THREAD

**Issue by DavidWells** [netlify/open-api#133]
Ref: https://github.com/netlify/product/issues/166

The https://open-api.netlify.com/#/default spec is missing the `https://api.netlify.com/oauth/token` endpoint

![image](https://user-images.githubusercontent.com/532272/51860573-f89b5100-22ee-11e9-80b2-9bdec46f0d7e.png)

This is used to fetch OAuth creds like so:

```
curl -d 'grant_type=client_credentials&client_id=<YOUR_CLIENT_ID>&client_secret=<YOUR_CLIENT_SECRET>' https://api.netlify.com/oauth/token
```

**Comment by kitop** [comment]
`client_credentials` flow is not supported.
