### ISSUE TITLE
Retrieve files list in a specific deploy

### ISSUE THREAD

**Issue by ruggerocastagnola** [netlify/open-api#160]
Hi there,

am I correct in assuming that there is currently no way of GETting the list of files for an older deploy? Something that would look like `/deploys/{deploy_id}/files`. I just found [uploadDeployFile](https://open-api.netlify.com/#/default/uploadDeployFile) but it is a PUT.

Basically, I need to check the hash assigned to a particular file name in several old deploys recursively (they are too many to do it by hand).

Thanks!

**Comment by ehmicky** [comment]
Hi @ruggerocastagnola,

First of all, sorry for the late response! 
It is possible to retrieve the URL of each individual file for a specific deploy by using the same URL you would see in your browser when previewing that deploy, such as 5d725e4e7108e8395da140c0--example-site.netlify.com.

Unfortunately, for implementation reasons, listing files is a complex operation that we don't intend to support at the very moment. You might solve this issue by manually keeping track of which files you've uploaded, although we do understand this might be cumbersome.

I am going to close this issue for tracking purpose, but please feel free to let us know what you think. Thanks!

**Comment by fool** [comment]
There's also a way to download the deploy from our UI, as shown in this screenshot, @ruggerocastagnola 

![image](https://user-images.githubusercontent.com/229024/65277004-d6ed1500-dadd-11e9-9dda-4b8ec5530833.png)


I know that's not what you asked for, but it is the best way besides knowing what was deployed, to find out what was deployed.  Use the link from the relevant deploys logs page - that link is specific to that deploy.

**Comment by ruggerocastagnola** [comment]
Hi all, thanks for the feedback. We ended up doing it manually this time, will keep that in mind if this pops up again.
