### ISSUE TITLE
[BUG] InstallationID is typed incorrectly

### ISSUE THREAD

**Issue by tnwhitwell** [netlify/open-api#162]
Hi,

It appears that `InstallationID` is typed incorrectly - it's specified as a `string`, but the API actually returns an integer, leading to unmarshal errors, as seen in the [Terraform provider](https://github.com/terraform-providers/terraform-provider-netlify/) when importing an existing instance:

```
Error: netlify_site.* (import id: *): 1 error occurred:
        * import netlify_site.* result: &: netlify_site.*: json: cannot unmarshal number into Go struct field RepoInfo.installation_id of type string
```
The offending line is:
https://github.com/netlify/open-api/blob/9abe15aefc5361a786b3559d58f44f0062cd26bd/go/models/repo_info.go#L37

And in swagger: https://github.com/netlify/open-api/blob/9abe15aefc5361a786b3559d58f44f0062cd26bd/swagger.yml#L1737-L1738

Thanks,

Tom

**Comment by sgrove** [comment]
I also just hit this and came to report the same issue!

**Comment by peckeltw** [comment]
Hi, 

any chance this will be merged soon? I face the same issue. Thanks!

**Comment by peckeltw** [comment]
Sorry, but the problem still exists. This is the debug output from Terraform trying to import the Netlify site:

> 2019/08/07 19:45:32 [DEBUG] ReferenceTransformer: "netlify_site.main" references: []
2019/08/07 19:45:32 [TRACE] Completed graph transform *terraform.ReferenceTransformer (no changes)
netlify_site.main: Refreshing state... [id=XXXXXX]
2019/08/07 19:45:32 [ERROR] <root>: eval: *terraform.EvalRefresh, err: json: cannot unmarshal number into Go struct field RepoInfo.installation_id of type string
2019/08/07 19:45:32 [ERROR] <root>: eval: *terraform.EvalSequence, err: json: cannot unmarshal number into Go struct field RepoInfo.installation_id of type string
2019/08/07 19:45:32 [TRACE] [walkRefresh] Exiting eval tree: netlify_site.main
2019/08/07 19:45:32 [TRACE] vertex "netlify_site.main": visit complete

> Error: json: cannot unmarshal number into Go struct field RepoInfo.installation_id of type string

I see the PR and the updated Swagger API documentation, but it still does not work. Any ideas how to solve this? 

Thanks,
Philipp

**Comment by Mongey** [comment]
@peckeltw #170 should fix this
