### ISSUE TITLE
Docs Nav Buggy

### ISSUE THREAD

**Issue by DavidWells** [netlify/open-api#213]
The sidebar is jumpy & disappears randomly. Makes navigating to stuff very difficult.

See: https://netlify.slack.com/files/UAY77K03B/FTXTZF9FB/open_api_docs_buggy.mp4

Idk what changed recently on the site. I don't remember this issue before

**Comment by ehmicky** [comment]
This is a bug of the library we use for generating the library (redoc) for Chrome `>= 80`: https://github.com/Redocly/redoc/issues/1167

Upgrading to the latest version of redoc should fix the issue.

**Comment by ehmicky** [comment]
This is now fixed in production.
