### ISSUE TITLE
Add support for Node 13

### ISSUE THREAD

**Issue by jpalumickas** [netlify/open-api#219]
Hey!

Current version of `@netlify/open-api` supports only Node v12 and we get this error:

@netlify/open-api@0.13.0: The engine "node" is incompatible with this module. Expected version "12". Got "13.8.0"

**Comment by ehmicky** [comment]
Hi @jpalumickas,

Thanks for reporting this! You are right, this is incorrect. I've opened the following PR to fix it: #220.

**Comment by ehmicky** [comment]
This has now been fixed in [`0.13.1`](https://github.com/netlify/open-api/releases/tag/v0.13.1).

**Comment by jpalumickas** [comment]
Thank you!! 🎉
