### ISSUE TITLE
Missing endpoints for oauth/applications for managing user tokens

### ISSUE THREAD

**Issue by pixelastic** [netlify/open-api#241]
As mentioned in https://community.netlify.com/t/support-guide-understanding-and-using-netlifys-api/160, I'm opening an issue about some missing endpoints:

- `GET oauth/applications` to get all user tokens
- `DELETE oauth/applications/{TOKEN_ID}` to delete a given token
- `POST oauth/applications/create_token` to create a new token

I found those endpoints by checking my dev tools in the dashboard and I managed to use them correctly from my code, but I couldn't find them documented in the open api website.

**Comment by kitop** [comment]
Hi @pixelastic, thanks for the issue!

Those endpoints are not documented on purpose. The request and response payload is not set yet, and may change anytime. We'd like to keep them this way until we're comfortable with a more final version.

**Comment by pixelastic** [comment]
Thanks for the feedback, that's good to know.

I'll keep using them in my code for now, but will keep an eye on possible failures.

Could you update this issue when/if they change?

Cheers

**Comment by fool** [comment]
I don't believe we can really commit to that, @pixelastic - you'll want to be checking return codes and monitoring and making sure your code reacts appropriately (e.g. alerts you if things stop working).  For our published API endpoints, it's a bit different of course; we try very hard not to make breaking changes (we add fields, but rarely remove any).  If we did make breaking changes to those published/documented/official API calls documented on https://open-api.netlify.com, we'd likely post that notice here in our updates (at a minimum):  https://community.netlify.com/c/features/updates/51

**Comment by pixelastic** [comment]
Sure, I understand. I know you're pretty good at following up on people requests, be it on the forum or on GitHub, so I wondered if that was something you could also do with undocumented endpoints. But I understand per the nature of the endpoint, this might not be doable.

Thanks
