### ISSUE TITLE
Get Build minutes in API

### ISSUE THREAD

**Issue by udahari** [netlify/open-api#271]
I want to get how many build minutes I have used on my account. but I can’t find in the docs, Can I get build minutes in API ?

**Comment by vbrown608** [comment]
Hi @udahari, thanks for the suggestion. This is available from the api at `/api/v1/{account_id}/builds/status`. We're working on adding it to the docs and our Javascript and Go clients libraries.

**Comment by vbrown608** [comment]
See docs at https://open-api.netlify.com/#operation/getAccountBuildStatus
