### ISSUE TITLE
Document clear_cache in createSiteBuild

### ISSUE THREAD

**Issue by tom-quiltt** [netlify/open-api#396]
You can pass clear_cache in [createSiteBuild](https://open-api.netlify.com/#tag/build) API.
Can we get this documented?

https://github.com/netlify/open-api/blob/5544cc4dd58f6f77bd94f275485e04da526cd5b3/swagger.yml#L1019

Thank you.

**Comment by kitop** [comment]
Good find!
Feel free to send a PR 😄

**Comment by kitop** [comment]
Closed via https://github.com/netlify/open-api/pull/399
