### ISSUE TITLE
Remove gobin in makefile in favor of plain go 

### ISSUE THREAD

**Issue by jasonbarry** [netlify/open-api#416]
There's a step in the makefile that depends on gobin, which has been archived as of Nov 8 of last year. We should use the normal go binary instead of depend on gobin.

**Comment by akahn** [comment]
Simply replacing `gobin run` with `go run` results in this error:

```
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

According to https://github.com/golang/go/issues/44840 there is no direct workaround for this issue, so we'll have to find a different solution.
