### ISSUE TITLE
Don't retry file uploads with `422` responses

### ISSUE THREAD

**Issue by JGAntunes** [netlify/open-api#476]
Following up on - https://github.com/netlify/pillar-support/issues/625

We should not be retrying file/function uploads which return 422. See [here](https://github.com/netlify/netlify-server/blob/main/server/request_file_upload.go#L101) for a better idea of the response codes we return.

**Comment by erikw** [comment]
Related: same idea for functions upload
https://github.com/netlify/functions-origin/issues/358

**Comment by JGAntunes** [comment]
Feels like this is already being worked on by dev foundations - https://github.com/netlify/open-api/pull/478 - going to close it 👍
