### ISSUE TITLE
Fix Incorrect Return Response for go version 1.21.1

### ISSUE THREAD

**Issue by MilanVaghasiya26** [netlify/open-api#499]
> When using Go version 1.21.1, there is an issue with the response handling inside the `ReadResponse` function in the `create_dns_record_responses.go` file. The current implementation does not correctly handle responses in certain scenarios, leading to incorrect results or unexpected behavior.
> 
> **Proposed Solution:**
> 
> I propose to investigate and fix the issue with the response handling in the `ReadResponse` function to ensure it works correctly with Go version 1.21.1.
> 
![image](https://github.com/netlify/open-api/assets/78582567/d84b0a0b-8742-4049-a83a-333cb4653057)

**Comment by lemonScaletech** [comment]
@minivan

**Comment by MilanVaghasiya26** [comment]
@lemonScaletech 
I already tried but **make generate** will erase the code changes

**Comment by lemonScaletech** [comment]
ohhhhhhh 
is it so ? I have also seen this problem.
Can you ping me once if this get done.

**Comment by mraerino** [comment]
i don't understand what your problem is? can you provide an example project that fails with 1.21.1? or a PR detailing the changes you tried to explain in your screenshot?

**Comment by MilanVaghasiya26** [comment]
First of all thanks for commenting.

I am a newbie and going through netlify, I have figured out the mistake. It was my bad.
But you should include a example. If you want I can created a PR for example. :)
cheers.
