### ISSUE TITLE
Inconsistency between API docs and Open API for updateSite operation

### ISSUE THREAD

**Issue by daveaglick** [netlify/open-api#50]
The API docs say:

> Takes all the same parameters as when creating a site.

That is specified in the API docs as `name`, `custom_domain`, `password`, `force_ssl`, `processing_settings` (see #47), and `repo`. However, the Open API specification indicates the body should contain the much more expansive `siteSetup` object.

**Comment by calavera** [comment]
All fields in that body should be optional. Open API is always more up to date than those docs and it's a better source of truth regarding what you can and cannot do.
