### ISSUE TITLE
No read/delete for deploy keys?

### ISSUE THREAD

**Issue by mitchellh** [netlify/open-api#52]
I'm working on a Terraform provider and noticed there is no read/delete endpoints for deploy keys. 

The primary sketchy thing about this for me is that Terraform can't verify that a deploy key is still valid. 

From a Netlify PoV, we'll likely be running nightly acceptance tests at some point that could create dozens if not a hundred or more deploy keys. Is it okay that these grow unbounded?

**Comment by calavera** [comment]
I just added those missing endpoints @mitchellh 🙌

**Comment by mitchellh** [comment]
Great! Thanks. Implemented now and works.
