### ISSUE TITLE
BuildHook payload is *models.Snippet, should it be *models.BuildHook?

### ISSUE THREAD

**Issue by mitchellh** [netlify/open-api#65]
Started to implement this TF resource but noticed this: https://github.com/netlify/open-api/blob/1d2abfd09b09266d93be5b26204df281867c3cb8/go/plumbing/operations/create_site_build_hook_responses.go#L56-L58

I believe that should be a `BuildHook`.

Thanks!

**Comment by calavera** [comment]
sorry about that, fixed! 🙌
