### ISSUE TITLE
Enable Let's Encrypt SSL

### ISSUE THREAD

**Issue by tiramiseb** [netlify/open-api#83]
Hello,

I'm trying to understand how I can enable SSL with Let's Encrypt (which would correspond to `POST /api/sites/{site_id}/ssl`) with the go library. It looks like noting is defined in the library for this.
Is there something I didn't find?

Moreover, once it will be enabled, is there a way to disable it?
According to https://www.netlify.com/docs/api/#sites, there is no way to disable it...

**Comment by fool** [comment]
This is enabled automatically now on every site with a custom domain, so no longer relevant.  If you have a site with a custom domain missing SSL, please contact the helpdesk (support@netlify.com) as we'd need to help untangle what is wrong.
