### ISSUE TITLE
Support for OAuth 2.0 Authorization Code Grant

### ISSUE THREAD

**Issue by leonardodino** [netlify/open-api#96]
I see there's [`Implicit Grant`](https://tools.ietf.org/html/draft-ietf-oauth-v2-31#section-4.2) implemented.
But I'm having trouble implementing a server-side [`Authorization Code Grant`](https://tools.ietf.org/html/draft-ietf-oauth-v2-31#section-4.1).

is it available but not documented? or unavailable at this time?

**Comment by leonardodino** [comment]
seems like the situation is reversed right now, the [dashboard](https://app.netlify.com/account/applications) provides us with `client_id` and `secret`. and seems like Implicit Grant always fails with `"Unknown Error"`.

the same requests that used to work at `/authorize` makes the server return status `500`, with the body: `{error: {}}`.

**Comment by leonardodino** [comment]
i don't see it officially documented, but right now it's working! 🎉 

Both the `code`, and `token` types seems to be supported,
besides the officially supported `ticket` type. horaay!

**Comment by bcomnes** [comment]
Rad, glad you got it working!  If you have ideas on how to make that more discoverable I would be happy to add a note or docs somewhere.

**Comment by M-ZubairAhmed** [comment]
Hi @leonardodino i am implementing code type, and i am struggling to find token url for netlify, where i can exchange by access code for token, do you know what that is? i cannot find it in documentaiton

**Comment by dangtony98** [comment]
Hey @M-ZubairAhmed @leonardodino!

Any updates on this? I'm looking for the code-token exchange as well as part of the server-side `Authorization Code Grant`. It'd help a lot as there doesn't seem to be any public documentation on this other than the `Implicit Grant` flow.
