### ISSUE TITLE
Ability to Delete a deploy

### ISSUE THREAD

**Issue by talves** [netlify/open-api#97]
I am wondering if it would be possible to have a `Delete` deploy.

Currently we can delete a site 
![image](https://user-images.githubusercontent.com/784848/43728680-ad4263ec-995a-11e8-80fe-4aa370393819.png)

Is it possible to have a DELETE **`/deploys/{deploy_id}`** ? or is that not possible?

**Comment by orliesaurus** [comment]
+1

**Comment by bcomnes** [comment]
We dont have this capability as of now, so we can't add it to the open-api spec.   Closing this issue until we have that endpoint available.

**Comment by talves** [comment]
Sounds good @bcomnes . I thought this was the case and have been telling people you can't delete a deploy. Mainly, just wanted to make sure I am not giving anyone wrong information also.
