### ISSUE TITLE
Missing DeleteSite on Porcelain Netlify client

### ISSUE THREAD

**Issue by Lanchi** [netlify/open-api#98]
I'm using Netlify client from porcelain package for site operations (create, deploy..). 
I want to implement site delete action (using site id), but I'm getting error `type *porcelain.Netlify has no field or method DeleteSite`.
I tried adding `DeleteSite` method to `site.go` in porcelain package (using `GetSite` from Netlify client as a pattern) just to see would it work, and it did, site got deleted.

Are you planning on adding this method to Netlify client?

---

I did manage to make it work by calling `Operations.DeleteSite` on Netlify client, but I also had to import plumbing operations package in order to get `NewDeleteSiteParams`. Site gets deleted, but this just doesn't look like a preferred way of doing it.
```go
import(
    netlify "github.com/netlify/open-api/go/porcelain"
    netlifyOperations "github.com/netlify/open-api/go/plumbing/operations"
)

func deleteNetlifySite(siteID string) {
    
    ...

    client := netlify.New(transport, strfmt.Default)
    resp, err := client.Operations.DeleteSite(netlifyOperations.NewDeleteSiteParams().WithSiteID(siteID), authInfo)
}
```

**Comment by ehmicky** [comment]
@Lanchi, sorry for the late response!
I believe this should be fixed with the latest version of the Go client. Could you please confirm?

**Comment by trey-watford** [comment]
@ehmicky I do not believe this has been corrected, My team and I just ran into this same issue, unless we are missing something.  Note that the docs for the porcelain package do not list a delete call here https://godoc.org/github.com/netlify/open-api/go/porcelain

**Comment by ehmicky** [comment]
@trey-watford Thanks for reporting this.

@mraerino Do you know what could the problem be?

**Comment by mraerino** [comment]
this is not a missing method. the way pointed out by the issue creator is the expected way right now.
if you want that as part of the lib, create a pull request, please.

**Comment by ehmicky** [comment]
Thanks for clarifying this @mraerino.

**Comment by reed-acst** [comment]
@mraerino put in a PR for the porcelain delete site method mentioned above here https://github.com/netlify/open-api/pull/210
